#项目和端口
server:
  context-path: /kyweb
  port: 8888

#数据库设置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kyweb_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#设定ftl文件路径
spring.freemarker.template-loader-path: classpath:/templates/



error.path: /error
#设定静态文件路径，js,css等
#spring.mvc.static-path-pattern: /static/**？
